// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "StrokeApp",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "StrokeApp",
            targets: ["AppModule"],
            bundleIdentifier: "com.ariuna.StrokeApp",
            teamIdentifier: "LU4XHFZPKM",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .lightningBolt),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Stroke App needs access to the Camera "),
                .speechRecognition(purposeString: "Stroke App needs access "),
                .microphone(purposeString: "Stroke App needs access to microphone")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/airbnb/lottie-ios.git", "4.0.0"..<"5.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Lottie", package: "lottie-ios")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)